# -*- coding: utf-8 -*-
"""C2_Transformation & Serving

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASjdY5AKvB_tehtaJjJlDbFDKHeNjJXb
"""

# Date 23 May 2024.
# Notes by Mr Akhona Njeje.
# Topic : Big Data Engineering fundamentals.
# Research work for AKH INDUSTRIES, Big Data Engineering department [Engineering].
# AKH INDUSTRIES has 3 DPT's : [AI] [Engieering] [Real Estate]. This is groud work for the Data Architecture of AKH INDUSTRIES.


# Notes:

# Data Engineering (DE) builds the foundation of AI, BI, Data science & Analytics.

# Transformation.

# Once data is ingested & stored, we need to transform it.
# Transformed data is useful for Analytics, AI & BI.
# Tranforming data can be changing strings to intergers, date types etc.
# Normalization is part of data Transformation.
#

# Data serving.

# This is the last stage of the DE life cycle.
# Analysts can be ready to build reports & AI Engineers can build the most sophisticated models, once this stage is met.
# Alot startups jump into AI prematurely, without setting the DE foundation right.

# Major undercurrents across the data engineering lifecycle.

### SECURITY. ### Data Management. ### Data Architecture. ### Software Engineering. ### Data Ops. ### Orchestration.

# SECURITY.

# DE's must understand both data & security access.
# DE's must give privileges to diffwerent users meaning giving a user or system access to only the essential data they need to perform there duty.
# DE's must be competent security administrators, they should understnad best practices on cloud & prem.

# Data Management.

# Without a framework for managing data, data engineers are simply technicians.
# Why is data management important? Cause it demonstrates that data is vital to daily operations.
# Data management ensures the quality, intergrity & security by an organisation.

# Data Management has the following:
### Data governance (accountability).
### Data modellling & design.
### Storage & operations.
### Data integration
### Ethics & PRIVACY.

# Data Architecture.

# Data Architecture reflects the current & future state of data systems that supports an org long term data needs & strategy.
# Architecture means knowing the trade offs with design, technologies, & tools in source systems.
# If Engineer collaborates with Architecture, the Engineer should able to deliver on the designs.

# Software Engineering (SE).

# SE is critically important to DE.
# The 1st DE's in the early 2000's where SE's who wrote frameworks like Mapreduce using C,C++ & Java.
# Good DE's has SE fundamentals & principles in place.