# -*- coding: utf-8 -*-
"""Chapter 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASjdY5AKvB_tehtaJjJlDbFDKHeNjJXb
"""

# Date 6 May 2024.
# Notes by Mr Akhona Njeje.
# Topic : Big Data Engineering fundamentals.
# Research work for AKH INDUSTRIES, Big Data Engineering department [Engineering].
# AKH INDUSTRIES has 3 DPT's : [AI] [Engieering] [Real Estate]. This is groud work for the Data Architecture of AKH INDUSTRIES.


# Notes:

# Data Engineering (DE) builds the foundation of AI, BI, Data science & analytics.

# What is Data Engineering (DE)?

# Its setting up of the org's infustructure, where we not only store data but get ready for consumption by Data scientists & analysts, bi developers, business analyts etc.
# DE is all about the movement, manipulation & management of data.
# DE is the dev, implementation & maintance of systems & processes that take in raw data & produce high quality, consistent information.
# DE is the intersection of security, data management, DataOps, data architecture, orchestration & software engineering.
# A Data Engineer manages the DE life cycle.

# There's types of DE

### 1st type is SQL focused DE.
### Data here is mainly in relation bd's.
### Sometimes, this data processing is done with an etl tool.

### 2nd type is big data focused DE.
### The primary storage of big data is in technologies like hadoop, casandra & hbase, the data processing is done by Spark, Mapreduce & Flink.
### Big data is the 3v's = volume + velocity + variety.
### Mapreduce was dev by google engineers, Hadoop was dev by Yahoo! engineers.
### Amazon also came to the party by creating elastic compute cloud (EC2), simple storage service (S3) & highly scalable NoSQL db's(DynamoDB) to keep up with big data explosion.
### Any1 can simply rent compute & storage from AWS.

# DE Life cycle.

# Data Generation ---> Storage (Ingestion, Transformation, Serving) ---> [Analytics][AI][BI]
# Undercurrents:
# Security + Data management + DataOps + Data Architecture + Software Engineering.