# -*- coding: utf-8 -*-
"""Final Chapter 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASjdY5AKvB_tehtaJjJlDbFDKHeNjJXb
"""

# Date 6 May 2024.
# Notes by Mr Akhona Njeje.
# Topic : Big Data Engineering fundamentals.
# Research work for AKH INDUSTRIES, Big Data Engineering department [Engineering].
# AKH INDUSTRIES has 3 DPT's : [AI] [Engieering] [Real Estate]. This is groud work for the Data Architecture of AKH INDUSTRIES.


# Notes:

# Data Engineering (DE) builds the foundation of AI, BI, Data science & analytics.

# What is Data Engineering (DE)?

# Its setting up of the org's infustructure, where we not only store data but get ready for consumption by Data scientists & analysts, bi developers, business analyts etc.
# DE is all about the movement, manipulation & management of data.
# DE is the dev, implementation & maintance of systems & processes that take in raw data & produce high quality, consistent information.
# DE is the intersection of security, data management, DataOps, data architecture, orchestration & software engineering.
# A Data Engineer manages the DE life cycle.

# There's types of DE

### 1st type is SQL focused DE.
### Data here is mainly in relation bd's.
### Sometimes, this data processing is done with an etl tool.

### 2nd type is big data focused DE.
### The primary storage of big data is in technologies like hadoop, casandra & hbase, the data processing is done by Spark, Mapreduce & Flink.
### Big data is the 3v's = volume + velocity + variety.
### Mapreduce was dev by google engineers, Hadoop was dev by Yahoo! engineers.
### Amazon also came to the party by creating elastic compute cloud (EC2), simple storage service (S3) & highly scalable NoSQL db's(DynamoDB) to keep up with big data explosion.
### Any1 can simply rent compute & storage from AWS.

# DE Life cycle.

# Data Generation ---> Storage (Ingestion, Transformation, Serving) ---> [Analytics][AI][BI]
# Undercurrents:
# Security + Data management + DataOps + Data Architecture + Software Engineering.

# 14 May. Continuing Chapter 1 from Orielly.



# Data Science & Engineering, how do they relate?

# Data Engineering is separate from Data Science & Analytics.
# Data Engineers build infustructure. Data Scientists they build powerful models & are researchers. Data Analytics are story tellers & greate communicators.

# Lets break the 3 roles into a triangle of needs:
### 1st level ---> COLLECTION = External data & Sensors.
### 2nd level ---> STORAGE = Pipelines, ETL development, Structured & Unstructured data storage.
### 3rd level ---> TRANSFORM = Cleaning, Preparation & Wrangling.
### 4th level ---> AGGREGATE = Analytics, Metrics, Training data & Feature engineering.
### 5th level ---> LEARN = Machine Learning, A/B Testing & Model development.
### 6th level ---> AI = AI, Deep Learning & Robotics.

# A solid data foundation is crucial, especially for the first 3 levels. Getting the 3 levels right, sets us up for building great AI & ML algorithms.
# Data Science drives Advance Analytics & ML. Data Engieering drives getting data & value from that acquired data.
# Data Engineering plays a huge role in making Data Science successful.
# [Data from various sources] ---> [Data Engineering] ---> [Data Science & Analytics].

# Data maturity. What is it?
### Refers to a progression toward higher data utalization, capabilities & integration across an organisation.

# Data maturity model followed by Data Engineers.
# [Starting with Data ---> Sclaling with Data ---> Leading with Data].
### Starting with data : At this stage the company is farely new to the data galaxy, the data team is very small. At this stage the Data Eng does everything.
### Scaling with data : At this stage the company plans to scale & looks far in the futrue where the co is data driven. Data Eng are more specialist here.
### Leading with data : At this stage the co is data-driven. The systems & pipelines are automated, consumers of data just perform self service analytics & ML.

# Primary tools of a DE(Data Engineers).
### SQL ---> For databaes & data lakes.
### Python ---> Python has a big eco system of DE frameworks.
### Java ---> Crucial for the Big Data eco system & Apache open source projects.
### Bash ---> Command line interface for Linux operating systems.

# Where do Data Engieers lie exactly amongst tech pro's.
### A = [Software Engineers, Data Architectures] ---> [Data Engineers] ---> B = [Data Analysts, Data Scientists]
### A = Its Data producers. B = Data consumer.